# .prettierrc or .prettierrc.yaml
trailingComma: 'es5'
tabWidth: 2
semi: true
singleQuote: true
overrides:
  - files:
      - '*.json'
      - '*.js'
      - '*.yml'
    options:
      singleQuote: false
  - files:
      - '*.ts'
      - '*.tsx'
