export const prescriptions = [
  {
    id: '1',
    name: 'Amoxicillin',
    dosage: '500mg',
    frequency: '3 times a day',
    pharmacyName: 'PharmaCare Plus',
    status: 'Ready for Pickup',
  },
  {
    id: '2',
    name: 'Ibuprofen',
    dosage: '200mg',
    frequency: 'Once a day',
    pharmacyName: 'HealthFirst Pharmacy',
    status: 'In Progress',
  },
  {
    id: '3',
    name: 'Lisinopril',
    dosage: '10mg',
    frequency: 'Daily',
    pharmacyName: 'WellnessRX',
    status: 'Filled',
  },
  {
    id: '4',
    name: 'Ibuprofen',
    dosage: '200mg',
    frequency: 'Once a day',
    pharmacyName: 'HealthFirst Pharmacy',
    status: 'In Progress',
  },
  {
    id: '5',
    name: 'Lisinopril',
    dosage: '10mg',
    frequency: 'Daily',
    pharmacyName: 'WellnessRX',
    status: 'Filled',
  },
  {
    id: '6',
    name: 'Ibuprofen',
    dosage: '200mg',
    frequency: 'Once a day',
    pharmacyName: 'HealthFirst Pharmacy',
    status: 'In Progress',
  },
  {
    id: '7',
    name: 'Lisinopril',
    dosage: '10mg',
    frequency: 'Daily',
    pharmacyName: 'WellnessRX',
    status: 'Filled',
  },
  {
    id: '8',
    name: '-',
    dosage: '-',
    frequency: '-',
    pharmacyName: 'HealthFirst Pharmacy',
    status: 'In Progress',
  },
];
